export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const SET_NOTIFICATION_ERROR = 'SET_NOTIFICATION_ERROR';
export const CLEAR_NOTIFICATION_ERROR = 'CLEAR_NOTIFICATION_ERROR';

export const OPEN_NAV_DRAWER = 'OPEN_NAV_DRAWER';
export const CLOSE_NAV_DRAWER = 'CLOSE_NAV_DRAWER';

export const GET_CATEGORIES_START = 'GET_CATEGORIES_START';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';
